# random seed
random_seed: 66

# data precision
precision: float32

# super parameters
dataset_start: 0
dataset_used: 10
te_dataset_start: 0
te_dataset_used: 20
time_start: 0
time_used: 2000
learning_rate: 2.5e-5
steplr_size: 200
steplr_gamma: 0.96
start_epoch: 0
epochs: 1000
window_size: 20
val_window_size: 20
te_window_size: 2000
batch_size: 1
num_workers: 4
window_shuffle: true

# network architecture
integral: 2
encoder_config:
  node_encoder_layers: [5, 16, 32, 64]   # [y:1 + pos:2 + node_type:2, ..., 64]
  edge_encoder_layers: [4, 16, 32, 64]  # [distance:1 + cartesian:2 + relative:1, ..., 64]

mpnn_block_config:
  mpnn_layers:
    - [192, 64, 64, 64, 64]   # phi: [h_i:64 + (h_j-h_i):64 + edge:64 = 192, ..., 64]
    - [128, 64, 64, 64, 64]   # gamma: [h:64 + aggr:64 = 128, ..., 64]
  mpnn_num: 5

decoder_config:
  node_decoder_layers: [64, 32, 16, 1]  # [MPNN输出:64, ..., 1]

laplace_block_config:
  in_dim: 3   # y:1 + pos:2
  h_dim: 24
  out_dim: 1

# experiment name and path
experiment_name: wave_expr_0
continuous_train: false
ckpt_path_tr: /home/wqx/projects/PhyMPGN/ckpts/wave_ckpt-{}-tr
ckpt_path_val: /home/wqx/projects/PhyMPGN/ckpts/wave_ckpt-{}-val
work_path: /home/wqx/projects/PhyMPGN

# data path
data_root_dir: /home/wqx/projects/PhyMPGN/data/wave
tr_processed_file: tr_data.pt
val_processed_file: val_data.pt
te_processed_file: te_data.pt

tr_raw_data: train_wave_10x2000x1161x1.h5
val_raw_data: train_wave_10x2000x1161x1.h5
te_raw_data: test_wave_20x2000x1161x1.h5

# log
log_file: /home/wqx/projects/PhyMPGN/logs/wave_out-{}.log
log_dir: /home/wqx/projects/PhyMPGN/runs/wave_expr_{}
